language: julia
os:
    - osx
    - linux
julia:
    - 1.3
    - nightly

matrix:
    allow_failure:
        - julia: nightly
    fast_finish: true

codecov: true

notifications:
    email: false

after_success:
  - julia -e 'cd(Pkg.dir("NeuroCore")); Pkg.add("Coverage"); using Coverage;
              Codecov.submit(Codecov.process_folder())'
